timer: 300
Random: false
UseTellRawMessages: false
Messages:
- '&f[&9Light&fof&dMoon&f] Дискорд сервер &ahttps://discord.gg/VhbRbn4zJJ'
- '&f[&9Light&fof&dMoon&f] Заходите к нам почаще!'
- '&f[&9Light&fof&dMoon&f] Есть вопросы? Смело пиши нам!'
TellRawMessages:
- '{"text":"&f[&9Light&fof&dMoon&f] Дискорд сервер &ahttps://discord.gg/VhbRbn4zJJ","clickEvent":{"action":"open_url","value":"https://discord.gg/VhbRbn4zJJ"}}'
- '{"text":"&f[&9Light&fof&dMoon&f] Заходите к нам почаще!"}'
- '{"text":"&f[&9Light&fof&dMoon&f] Есть вопросы? Смело пиши нам!"}'
